# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'SDCycleScrollView','~> 1.64'
pod 'AFNetworking', '~>3.1.0'
pod 'JSONModel', '~> 1.2.0'
pod 'JPush'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
pod 'MJRefresh'
pod 'AMap2DMap' #2D地图SDK
pod 'AMapSearch' #搜索功能
pod 'AMapLocation'
pod 'ZLPhotoBrowser'
pod 'IQKeyboardManager'
pod 'TZImagePickerController'
pod 'Masonry'
target 'SKSpaceService' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SKSpaceService

  target 'SKSpaceServiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SKSpaceServiceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
